"""agregar_campo_imagen

Revision ID: c939fae0f2e1
Revises: 612fc570a068
Create Date: 2023-11-12 12:46:22.147624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c939fae0f2e1'
down_revision: Union[str, None] = '612fc570a068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habitaciones', sa.Column('imagen', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habitaciones', 'imagen')
    # ### end Alembic commands ###
