"""agregar_campo_nombre

Revision ID: db6ee1c4f773
Revises: c939fae0f2e1
Create Date: 2023-11-12 12:50:33.835629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db6ee1c4f773'
down_revision: Union[str, None] = 'c939fae0f2e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('habitaciones', sa.Column('nombre', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('habitaciones', 'nombre')
    # ### end Alembic commands ###
